// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: author.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create_author = `-- name: create_author :one
INSERT INTO authors ( 
    name, bio, email
) VALUES (
    $1, $2, $3
)
RETURNING id, name, bio, email
`

type create_authorParams struct {
	Name  string
	Bio   pgtype.Text
	Email string
}

func (q *Queries) create_author(ctx context.Context, arg create_authorParams) (Author, error) {
	row := q.db.QueryRow(ctx, create_author, arg.Name, arg.Bio, arg.Email)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Email,
	)
	return i, err
}
